# -*- coding: utf-8 -*-
"""
5.0.31：缩略图保持原宽高比 + 一批图片「显示第一张、点开左右滑动」

改动清单
  1. pages/Index.ets
     - 新增 mediaRatio（路径->宽高比）/ thumbTick / chatMediaGroups / gallery* 状态
     - 新增 mediaThumb（等比缩略图）、mediaPreviewPage（画廊单页）、
       openMediaGallery / openChatGallery / openFileGallery、ensureMediaRatio、
       thumbW/thumbH/ratioOf/clampRatio/baseName/splitFileNames 等辅助
     - 视频首帧不再请求 192x192（会把 16:9 拉成 1:1），改取原尺寸再等比缩到 320
     - 聊天气泡：一批图只出第一张 + 「共 N 张」角标
     - 全屏预览：>1 张时用 Swiper，可左右滑动
  2. service/LanService.ets
     - ChatMessage 新增 files（一批文件名，'\n' 分隔），落盘/恢复都带上
  3. service/FileTransfer.ets / service/V5Transfer.ets
     - TransferReport 新增 fileNames，终态上报带上整批文件名

幂等：先查哨兵 GALLERY_5031，已打过直接退出。
"""
import io
import os
import sys

ROOT = r'E:\lanshare-harmony\LANShareV5'
IDX = os.path.join(ROOT, 'entry', 'src', 'main', 'ets', 'pages', 'Index.ets')
LAN = os.path.join(ROOT, 'entry', 'src', 'main', 'ets', 'service', 'LanService.ets')
FT = os.path.join(ROOT, 'entry', 'src', 'main', 'ets', 'service', 'FileTransfer.ets')
V5 = os.path.join(ROOT, 'entry', 'src', 'main', 'ets', 'service', 'V5Transfer.ets')

SENTINEL = 'GALLERY_5031'


def load(p):
    with io.open(p, encoding='utf-8', newline='') as f:
        return f.read()


docs = {}
for p in (IDX, LAN, FT, V5):
    docs[p] = load(p)

if SENTINEL in docs[IDX]:
    print('ALREADY APPLIED')
    sys.exit(0)

# ==================================================================
# 待替换片段（old -> new），先全部校验、最后统一落盘
# ==================================================================
edits = []


def add(path, old, new, tag):
    edits.append((path, old, new, tag))


# ---------------- A. Index.ets：字段 ----------------
OLD_A = (
    "  /** 每条消息 id -> 其「收到的图片/视频」沙箱路径；空串 = 无缩略图。见 syncChatMediaPaths */\n"
    "  @State chatMediaPaths: Map<string, string> = new Map<string, string>();\n"
)
NEW_A = OLD_A + (
    "  /**\n"
    "   * 每条消息 id -> 这一批媒体文件的沙箱路径（顺序 = 传输顺序）。\n"
    "   *\n"
    "   * ⚠️ 5.0.31：对端一次发来 N 张图时，聊天里只有**一条**「N 个文件」记录\n"
    "   *    （`FileTransfer` 的终态上报就是一个合并文件名），老逻辑按名字反查不到任何媒体，\n"
    "   *    于是只能显示一行干巴巴的文字。现在从 `ChatMessage.files` 拿到整批名字，\n"
    "   *    逐个反查成路径 —— 气泡出第一张缩略图，点开进画廊左右滑。\n"
    "   */\n"
    "  @State chatMediaGroups: Map<string, string[]> = new Map<string, string[]>();\n"
    "  /** 上一次算出来的分组签名，避免每次刷新都换引用（见 syncChatMediaPaths） */\n"
    "  private chatMediaGroupsSig: string = '';\n"
    "  /**\n"
    "   * 5.0.31：媒体路径 -> **原图宽高比**（w/h）。\n"
    "   *\n"
    "   * 缩略图以前是写死的 128×128 / 48×48 配 `objectFit(Cover)` —— 非正方形原图\n"
    "   * 会被**裁成正方形**，再叠上 192×192 的解码请求（视频首帧）就是双重变形。\n"
    "   * 现在按真实比例出框，解码尺寸也按同一个比例给，全程等比缩放。\n"
    "   */\n"
    "  private mediaRatio: Map<string, number> = new Map<string, number>();\n"
    "  /** 正在量尺寸的路径（防重复提交） */\n"
    "  private mediaRatioBusy: Set<string> = new Set<string>();\n"
    "  /** 每量出一个比例就 +1；@State 变化 -> 重新 build -> 缩略图换成等比框 */\n"
    "  @State thumbTick: number = 0;\n"
    "  /** 全屏预览的「一批」媒体路径（单张时长度为 1） */\n"
    "  @State galleryPaths: string[] = [];\n"
    "  /** 与 galleryPaths 一一对应的显示名（存相册 / 顶栏用） */\n"
    "  @State galleryNames: string[] = [];\n"
    "  /** 画廊当前页下标 */\n"
    "  @State galleryIndex: number = 0;\n"
    "  private swiperCtl: SwiperController = new SwiperController();\n"
)
add(IDX, OLD_A, NEW_A, 'A.字段')

# ---------------- B. Index.ets：syncChatMediaPaths ----------------
OLD_B = (
    "  private syncChatMediaPaths(): void {\n"
    "    const m: Map<string, string> = new Map<string, string>();\n"
    "    for (let i = 0; i < this.chat.length; i++) {\n"
    "      const msg: ChatMessage = this.chat[i];\n"
    "      let p: string = '';\n"
    "      if (msg.kind === 'file' && msg.incoming && this.isMediaName(msg.content)) {\n"
    "        const hit: string | undefined = this.recvIndex.get(msg.content);\n"
    "        if (hit !== undefined) {\n"
    "          p = hit;\n"
    "        }\n"
    "      }\n"
    "      m.set(msg.id, p);\n"
    "    }\n"
    "    // 内容没变就不换引用，避免无谓重绘（文件页刷新很频繁）\n"
    "    if (this.chatMediaPaths.size === m.size) {\n"
    "      let same: boolean = true;\n"
    "      for (const key of m.keys()) {\n"
    "        if (this.chatMediaPaths.get(key) !== m.get(key)) {\n"
    "          same = false;\n"
    "          break;\n"
    "        }\n"
    "      }\n"
    "      if (same) {\n"
    "        return;\n"
    "      }\n"
    "    }\n"
    "    this.chatMediaPaths = m;\n"
    "  }\n"
)
NEW_B = (
    "  private syncChatMediaPaths(): void {\n"
    "    const m: Map<string, string> = new Map<string, string>();\n"
    "    const g: Map<string, string[]> = new Map<string, string[]>();\n"
    "    let sig: string = '';\n"
    "    for (let i = 0; i < this.chat.length; i++) {\n"
    "      const msg: ChatMessage = this.chat[i];\n"
    "      let p: string = '';\n"
    "      const paths: string[] = [];\n"
    "      if (msg.kind === 'file' && msg.incoming) {\n"
    "        if (this.isMediaName(msg.content)) {\n"
    "          const hit: string | undefined = this.recvIndex.get(msg.content);\n"
    "          if (hit !== undefined) {\n"
    "            p = hit;\n"
    "          }\n"
    "        }\n"
    "        // 5.0.31：一批文件 —— 逐个名字反查路径，只收「能直接看」的那几类。\n"
    "        // ⚠️ 去重按**路径**：同一张图被登记了两个键时别重复进画廊。\n"
    "        if (msg.files.length > 0) {\n"
    "          const names: string[] = Index.splitFileNames(msg.files);\n"
    "          for (let k = 0; k < names.length; k++) {\n"
    "            if (!this.isMediaName(names[k])) {\n"
    "              continue;\n"
    "            }\n"
    "            const hit2: string | undefined = this.recvIndex.get(names[k]);\n"
    "            if (hit2 !== undefined && !paths.includes(hit2)) {\n"
    "              paths.push(hit2);\n"
    "            }\n"
    "          }\n"
    "          if (p.length === 0 && paths.length > 0) {\n"
    "            p = paths[0];\n"
    "          }\n"
    "        }\n"
    "      }\n"
    "      m.set(msg.id, p);\n"
    "      g.set(msg.id, paths);\n"
    "      // 缩放框要按真实比例出，先把比例量出来（同步读头信息，不解码）\n"
    "      if (p.length > 0) {\n"
    "        this.ensureMediaRatio(p);\n"
    "      }\n"
    "      for (let k = 0; k < paths.length; k++) {\n"
    "        this.ensureMediaRatio(paths[k]);\n"
    "      }\n"
    "      sig += `${msg.id}:${paths.join(',')};`;\n"
    "    }\n"
    "    // 分组：签名没变就不换引用（下面那张表同理）\n"
    "    if (sig !== this.chatMediaGroupsSig) {\n"
    "      this.chatMediaGroupsSig = sig;\n"
    "      this.chatMediaGroups = g;\n"
    "    }\n"
    "    // 内容没变就不换引用，避免无谓重绘（文件页刷新很频繁）\n"
    "    if (this.chatMediaPaths.size === m.size) {\n"
    "      let same: boolean = true;\n"
    "      for (const key of m.keys()) {\n"
    "        if (this.chatMediaPaths.get(key) !== m.get(key)) {\n"
    "          same = false;\n"
    "          break;\n"
    "        }\n"
    "      }\n"
    "      if (same) {\n"
    "        return;\n"
    "      }\n"
    "    }\n"
    "    this.chatMediaPaths = m;\n"
    "  }\n"
)
add(IDX, OLD_B, NEW_B, 'B.syncChatMediaPaths')

# ---------------- C. Index.ets：open/close 预览 + 新增一批辅助 ----------------
OLD_C = (
    "  private openMediaPreview(path: string, name: string): void {\n"
    "    this.imgPreview = path;\n"
    "    this.imgPreviewName = name;\n"
    "    // 一个路径，两套渲染 —— 靠这个标记分流\n"
    "    this.imgPreviewVideo = this.isVideoName(name);\n"
    "    this.imgScale = 1;\n"
    "    this.imgPinchBase = 1;\n"
    "    this.imgOffX = 0;\n"
    "    this.imgOffY = 0;\n"
    "  }\n"
    "\n"
    "  /** 关闭全屏预览并复位缩放 / 位移（否则下一张图会带着上一张的倍率打开） */\n"
    "  private closeMediaPreview(): void {\n"
    "    // 视频先停：浮层虽然会被销毁，但显式停掉更保险（别让声音多跑半秒）\n"
    "    try {\n"
    "      this.videoCtl.stop();\n"
    "    } catch (e) {\n"
    "      // 没在播放时 stop 会抛，忽略\n"
    "    }\n"
    "    this.imgPreview = '';\n"
    "    this.imgPreviewName = '';\n"
    "    this.imgPreviewVideo = false;\n"
    "    this.imgScale = 1;\n"
    "    this.imgPinchBase = 1;\n"
    "    this.imgOffX = 0;\n"
    "    this.imgOffY = 0;\n"
    "  }\n"
)
NEW_C = (
    "  private openMediaPreview(path: string, name: string): void {\n"
    "    this.openMediaGallery([path], [name], 0);\n"
    "  }\n"
    "\n"
    "  /**\n"
    "   * 5.0.31：打开一批媒体（>=1 个），从第 `index` 张开始看。\n"
    "   *\n"
    "   * ⚠️ 单张时也走这里 —— 只是长度为 1，画廊不启用 Swiper，行为与 5.0.30 完全一致，\n"
    "   *    已验证过的「单图缩放预览」那条路径一个字都没动。\n"
    "   * ⚠️ 视频也要顺手预热首帧：画廊里非当前页是靠首帧当占位图的。\n"
    "   */\n"
    "  private openMediaGallery(paths: string[], names: string[], index: number): void {\n"
    "    if (paths.length === 0) {\n"
    "      return;\n"
    "    }\n"
    "    this.galleryPaths = paths;\n"
    "    this.galleryNames = names;\n"
    "    let at: number = index < 0 ? 0 : index;\n"
    "    if (at >= paths.length) {\n"
    "      at = paths.length - 1;\n"
    "    }\n"
    "    this.galleryIndex = at;\n"
    "    for (let i = 0; i < paths.length; i++) {\n"
    "      if (this.isVideoName(this.galleryNameAt(i))) {\n"
    "        this.ensureVideoThumb(paths[i]);\n"
    "      }\n"
    "    }\n"
    "    this.imgPreview = paths[at];\n"
    "    this.imgPreviewName = this.galleryNameAt(at);\n"
    "    // 一个路径，两套渲染 —— 靠这个标记分流\n"
    "    this.imgPreviewVideo = this.isVideoName(this.imgPreviewName);\n"
    "    this.imgScale = 1;\n"
    "    this.imgPinchBase = 1;\n"
    "    this.imgOffX = 0;\n"
    "    this.imgOffY = 0;\n"
    "  }\n"
    "\n"
    "  /** 画廊翻页：停掉上一个视频、换当前项、复位缩放 */\n"
    "  private onGalleryPageChanged(idx: number): void {\n"
    "    if (idx === this.galleryIndex || idx < 0 || idx >= this.galleryPaths.length) {\n"
    "      return;\n"
    "    }\n"
    "    try {\n"
    "      this.videoCtl.stop();\n"
    "    } catch (e) {\n"
    "      // 没在播放时 stop 会抛，忽略\n"
    "    }\n"
    "    this.galleryIndex = idx;\n"
    "    this.imgPreview = this.galleryPaths[idx];\n"
    "    this.imgPreviewName = this.galleryNameAt(idx);\n"
    "    this.imgPreviewVideo = this.isVideoName(this.imgPreviewName);\n"
    "    this.imgScale = 1;\n"
    "    this.imgPinchBase = 1;\n"
    "    this.imgOffX = 0;\n"
    "    this.imgOffY = 0;\n"
    "  }\n"
    "\n"
    "  /** 画廊第 i 项的显示名（越界时退回当前项） */\n"
    "  private galleryNameAt(i: number): string {\n"
    "    if (i >= 0 && i < this.galleryNames.length && this.galleryNames[i].length > 0) {\n"
    "      return this.galleryNames[i];\n"
    "    }\n"
    "    if (i >= 0 && i < this.galleryPaths.length) {\n"
    "      return Index.baseName(this.galleryPaths[i]);\n"
    "    }\n"
    "    return this.imgPreviewName;\n"
    "  }\n"
    "\n"
    "  /** 消息气泡：打开这一批（从第 index 张看起） */\n"
    "  private openChatGallery(id: string, index: number): void {\n"
    "    const paths: string[] = this.mediaPathsOf(id);\n"
    "    if (paths.length === 0) {\n"
    "      return;\n"
    "    }\n"
    "    const names: string[] = [];\n"
    "    for (let i = 0; i < paths.length; i++) {\n"
    "      names.push(Index.baseName(paths[i]));\n"
    "    }\n"
    "    this.openMediaGallery(paths, names, index);\n"
    "  }\n"
    "\n"
    "  /**\n"
    "   * 「文件」页：点一张图/视频时，把**整个列表里的媒体**都装进画廊，\n"
    "   * 从点中那一项开始看 —— 收到一批图时同样是左右滑。\n"
    "   */\n"
    "  private openFileGallery(f: ReceivedFile): void {\n"
    "    const paths: string[] = [];\n"
    "    const names: string[] = [];\n"
    "    let at: number = 0;\n"
    "    for (let i = 0; i < this.receivedFiles.length; i++) {\n"
    "      const g: ReceivedFile = this.receivedFiles[i];\n"
    "      if (!this.isMediaName(g.name)) {\n"
    "        continue;\n"
    "      }\n"
    "      if (g.path === f.path) {\n"
    "        at = paths.length;\n"
    "      }\n"
    "      paths.push(g.path);\n"
    "      names.push(g.name);\n"
    "    }\n"
    "    if (paths.length === 0) {\n"
    "      this.openMediaPreview(f.path, f.name);\n"
    "      return;\n"
    "    }\n"
    "    this.openMediaGallery(paths, names, at);\n"
    "  }\n"
    "\n"
    "  /**\n"
    "   * 量一张图的真实宽高比（**只读头信息，不解码**）。\n"
    "   *\n"
    "   * ⚠️ 视频不走这里：它的比例从解出来的首帧 PixelMap 上取（见 decodeVideoThumb），\n"
    "   *    `createImageSource` 喂 mp4 只会抛错。\n"
    "   */\n"
    "  private ensureMediaRatio(path: string): void {\n"
    "    if (path.length === 0 || this.mediaRatio.has(path) || this.mediaRatioBusy.has(path)) {\n"
    "      return;\n"
    "    }\n"
    "    if (this.isVideoName(path)) {\n"
    "      return;\n"
    "    }\n"
    "    this.mediaRatioBusy.add(path);\n"
    "    try {\n"
    "      const src: image.ImageSource = image.createImageSource(path);\n"
    "      const info: image.ImageInfo = src.getImageInfoSync(0);\n"
    "      const w: number = info.size.width;\n"
    "      const h: number = info.size.height;\n"
    "      if (w > 0 && h > 0) {\n"
    "        this.mediaRatio.set(path, Index.clampRatio(w / h));\n"
    "        this.thumbTick++;\n"
    "      }\n"
    "      try {\n"
    "        src.release();\n"
    "      } catch (x) {\n"
    "        // 释放失败不影响显示\n"
    "      }\n"
    "    } catch (e) {\n"
    "      const err: BusinessError = e as BusinessError;\n"
    "      Log.w(TAG, `读图片尺寸失败: ${err.code} ${path}`);\n"
    "    } finally {\n"
    "      this.mediaRatioBusy.delete(path);\n"
    "    }\n"
    "  }\n"
    "\n"
    "  /** 缩略图框宽：最长边 = maxSide，按原图比例算 */\n"
    "  private thumbW(path: string, maxSide: number): number {\n"
    "    const r: number = this.ratioOf(path);\n"
    "    return r >= 1 ? maxSide : Math.round(maxSide * r);\n"
    "  }\n"
    "\n"
    "  /** 缩略图框高：最长边 = maxSide，按原图比例算 */\n"
    "  private thumbH(path: string, maxSide: number): number {\n"
    "    const r: number = this.ratioOf(path);\n"
    "    return r >= 1 ? Math.round(maxSide / r) : maxSide;\n"
    "  }\n"
    "\n"
    "  /**\n"
    "   * 这条路径的宽高比（量不到就按 1 = 正方形）。\n"
    "   *\n"
    "   * ⚠️ 读一下 `thumbTick` 是为了**建立 @State 依赖**：比例是异步量出来的，\n"
    "   *    不建立依赖的话框尺寸永远停在首次渲染的正方形。\n"
    "   */\n"
    "  private ratioOf(path: string): number {\n"
    "    if (this.thumbTick < 0) {\n"
    "      return 1;\n"
    "    }\n"
    "    const v: number | undefined = this.mediaRatio.get(path);\n"
    "    return v === undefined ? 1 : v;\n"
    "  }\n"
    "\n"
    "  /** 极端长图 / 全景图别把框拉成一条线；夹到 [0.45, 2.2]（约 9:20 ~ 22:10） */\n"
    "  private static clampRatio(r: number): number {\n"
    "    if (r > 2.2) {\n"
    "      return 2.2;\n"
    "    }\n"
    "    if (r < 0.45) {\n"
    "      return 0.45;\n"
    "    }\n"
    "    return r;\n"
    "  }\n"
    "\n"
    "  /** 绝对路径 -> 文件名 */\n"
    "  private static baseName(path: string): string {\n"
    "    const s: number = path.lastIndexOf('/');\n"
    "    return s >= 0 ? path.substring(s + 1) : path;\n"
    "  }\n"
    "\n"
    "  /** `ChatMessage.files` 的 '\n' 分隔还原成数组（文件名里不会有换行） */\n"
    "  private static splitFileNames(s: string): string[] {\n"
    "    const out: string[] = [];\n"
    "    let cur: string = '';\n"
    "    for (let i = 0; i < s.length; i++) {\n"
    "      const c: string = s.charAt(i);\n"
    "      if (c === '\\n') {\n"
    "        if (cur.length > 0) {\n"
    "          out.push(cur);\n"
    "        }\n"
    "        cur = '';\n"
    "      } else {\n"
    "        cur += c;\n"
    "      }\n"
    "    }\n"
    "    if (cur.length > 0) {\n"
    "      out.push(cur);\n"
    "    }\n"
    "    return out;\n"
    "  }\n"
    "\n"
    "  /** 这条消息那一批媒体的路径（空数组 = 不是媒体 / 还没落盘） */\n"
    "  private mediaPathsOf(id: string): string[] {\n"
    "    const v: string[] | undefined = this.chatMediaGroups.get(id);\n"
    "    return v === undefined ? [] : v;\n"
    "  }\n"
    "\n"
    "  private mediaCountOf(id: string): number {\n"
    "    return this.mediaPathsOf(id).length;\n"
    "  }\n"
    "\n"
    "  /** 第 i 个媒体的路径（越界给空串，调用方按「没有缩略图」处理） */\n"
    "  private mediaPathAt(id: string, i: number): string {\n"
    "    const v: string[] = this.mediaPathsOf(id);\n"
    "    return i >= 0 && i < v.length ? v[i] : '';\n"
    "  }\n"
    "\n"
    "  /** 气泡底部那行提示（一批 / 单个 / 无缩略图三种） */\n"
    "  private bubbleHintOf(m: ChatMessage, mediaPath: string): string {\n"
    "    const n: number = this.mediaCountOf(m.id);\n"
    "    if (n > 1) {\n"
    "      return `点击查看 ${n} 张 · 长按存相册`;\n"
    "    }\n"
    "    if (n === 1 || mediaPath.length > 0) {\n"
    "      const nm: string = mediaPath.length > 0 ? mediaPath : m.content;\n"
    "      return this.isVideoName(nm) ? '点击播放 · 长按存相册' : '点击看图 · 长按存相册';\n"
    "    }\n"
    "    return '点击查看 ›';\n"
    "  }\n"
    "\n"
    "  /** 关闭全屏预览并复位缩放 / 位移（否则下一张图会带着上一张的倍率打开） */\n"
    "  private closeMediaPreview(): void {\n"
    "    // 视频先停：浮层虽然会被销毁，但显式停掉更保险（别让声音多跑半秒）\n"
    "    try {\n"
    "      this.videoCtl.stop();\n"
    "    } catch (e) {\n"
    "      // 没在播放时 stop 会抛，忽略\n"
    "    }\n"
    "    this.imgPreview = '';\n"
    "    this.imgPreviewName = '';\n"
    "    this.imgPreviewVideo = false;\n"
    "    this.imgScale = 1;\n"
    "    this.imgPinchBase = 1;\n"
    "    this.imgOffX = 0;\n"
    "    this.imgOffY = 0;\n"
    "    this.galleryPaths = [];\n"
    "    this.galleryNames = [];\n"
    "    this.galleryIndex = 0;\n"
    "  }\n"
)
add(IDX, OLD_C, NEW_C, 'C.open/close + 辅助')

# ---------------- D. Index.ets：视频首帧不再解成正方形 ----------------
OLD_D = (
    "      const pp: media.PixelMapParams = { width: 192, height: 192 };\n"
    "      const pm: image.PixelMap = await gen.fetchFrameByTime(\n"
    "        0, media.AVImageQueryOptions.AV_IMAGE_QUERY_CLOSEST_SYNC, pp);\n"
    "      this.videoThumbs.set(path, pm);\n"
    "      // @State 计数器自增 —— Map 本身不是可观察对象，靠它把重绘踢起来\n"
    "      this.videoThumbTick++;\n"
)
NEW_D = (
    "      // ⚠️ 5.0.31：**不能**再传 {width:192,height:192}。PixelMapParams 的语义是\n"
    "      //    「按给定宽高缩放」（SDK media.d.ts：值须 >0 且 <= 原视频宽高，否则不缩放），\n"
    "      //    给正方形就是把 16:9 硬拉成 1:1 —— 视频缩略图变形的根因。\n"
    "      //    这里传 -1 取**原尺寸首帧**，量出真实比例后再等比缩到 320 以内。\n"
    "      let pm: image.PixelMap | null = null;\n"
    "      try {\n"
    "        pm = await gen.fetchFrameByTime(\n"
    "          0, media.AVImageQueryOptions.AV_IMAGE_QUERY_CLOSEST_SYNC, { width: -1, height: -1 });\n"
    "      } catch (e1) {\n"
    "        // 个别版本不接受 -1：退回固定尺寸，宁可小一点也不留空白\n"
    "        pm = await gen.fetchFrameByTime(\n"
    "          0, media.AVImageQueryOptions.AV_IMAGE_QUERY_CLOSEST_SYNC, { width: 192, height: 192 });\n"
    "      }\n"
    "      if (pm !== null) {\n"
    "        try {\n"
    "          const info: image.ImageInfo = pm.getImageInfoSync();\n"
    "          const vw: number = info.size.width;\n"
    "          const vh: number = info.size.height;\n"
    "          if (vw > 0 && vh > 0) {\n"
    "            this.mediaRatio.set(path, Index.clampRatio(vw / vh));\n"
    "            const longest: number = vw > vh ? vw : vh;\n"
    "            if (longest > 320) {\n"
    "              const s: number = 320 / longest;\n"
    "              await pm.scale(s, s);\n"
    "            }\n"
    "          }\n"
    "        } catch (x) {\n"
    "          // 量不到比例就按正方形处理，不影响显示\n"
    "        }\n"
    "        this.videoThumbs.set(path, pm);\n"
    "        // @State 计数器自增 —— Map 本身不是可观察对象，靠它把重绘踢起来\n"
    "        this.videoThumbTick++;\n"
    "        this.thumbTick++;\n"
    "      }\n"
)
add(IDX, OLD_D, NEW_D, 'D.视频首帧比例')

# ---------------- E. Index.ets：全屏预览 -> 画廊 ----------------
OLD_E = (
    "  @Builder\n"
    "  imgPreviewView() {\n"
    "    if (this.imgPreview.length > 0) {\n"
    "      Stack({ alignContent: Alignment.Top }) {\n"
    "        if (this.imgPreviewVideo) {\n"
)
NEW_E = (
    "  @Builder\n"
    "  imgPreviewView() {\n"
    "    if (this.imgPreview.length > 0) {\n"
    "      Stack({ alignContent: Alignment.Top }) {\n"
    "        if (this.galleryPaths.length > 1) {\n"
    "          // 5.0.31：一批图 —— Swiper 左右滑。单张时**不**走这里，\n"
    "          //    保持 5.0.30 那条已验证的单图预览路径不动。\n"
    "          Swiper({ index: this.galleryIndex, controller: this.swiperCtl }) {\n"
    "            ForEach(this.galleryPaths, (p: string, i: number) => {\n"
    "              this.mediaPreviewPage(p, this.galleryNameAt(i), i === this.galleryIndex)\n"
    "            }, (p: string) => p)\n"
    "          }\n"
    "          .width('100%')\n"
    "          .height('100%')\n"
    "          .loop(false)\n"
    "          .indicator(false)\n"
    "          .cachedCount(1)\n"
    "          .onChange((idx: number) => {\n"
    "            this.onGalleryPageChanged(idx);\n"
    "          })\n"
    "        } else {\n"
    "          this.mediaPreviewPage(this.imgPreview, this.imgPreviewName, true)\n"
    "        }\n"
    "\n"
    "        // 顶栏：文件名 + 关闭。文件名占满剩余宽度，放不下就省略号\n"
    "        Row({ space: 10 }) {\n"
    "          Text(this.imgPreviewName)\n"
    "            .fontSize(13)\n"
    "            .fontColor('#EAEAEA')\n"
    "            .layoutWeight(1)\n"
    "            .maxLines(1)\n"
    "            .textOverflow({ overflow: TextOverflow.Ellipsis })\n"
    "          if (this.galleryPaths.length > 1) {\n"
    "            Text(`${this.galleryIndex + 1}/${this.galleryPaths.length}`)\n"
    "              .fontSize(13)\n"
    "              .fontColor('#EAEAEA')\n"
    "          }\n"
    "          Button('存相册')\n"
    "            .fontSize(13)\n"
    "            .height(32)\n"
    "            .padding({ left: 14, right: 14 })\n"
    "            .backgroundColor('#33FFFFFF')\n"
    "            .fontColor(Color.White)\n"
    "            .onClick(() => this.saveImageToAlbum(this.imgPreview, this.imgPreviewName))\n"
    "          Button('关闭')\n"
    "            .fontSize(13)\n"
    "            .height(32)\n"
    "            .padding({ left: 14, right: 14 })\n"
    "            .backgroundColor('#33FFFFFF')\n"
    "            .fontColor(Color.White)\n"
    "            .onClick(() => this.closeMediaPreview())\n"
    "        }\n"
    "        .width('100%')\n"
    "        .padding({ left: 16, right: 16, top: this.topInset + 10 })\n"
    "      }\n"
    "      .width('100%')\n"
    "      .height('100%')\n"
    "      // 近黑底：看照片时最不干扰\n"
    "      .backgroundColor('#F0000000')\n"
    "    }\n"
    "  }\n"
    "\n"
    "  /**\n"
    "   * 画廊的一页（图片 = 缩放预览；视频 = 播放器）。\n"
    "   *\n"
    "   * ⚠️ 只有**当前页**才挂 `Video`：多个 Video 共用同一个 `VideoController`\n"
    "   *    行为未定义（stop 到底停哪个说不清），所以非当前页退回首帧缩略图 + ▶。\n"
    "   */\n"
    "  @Builder\n"
    "  mediaPreviewPage(path: string, name: string, active: boolean) {\n"
    "    Stack({ alignContent: Alignment.Center }) {\n"
    "      if (this.isVideoName(name)) {\n"
    "        if (active) {\n"
)
add(IDX, OLD_E, NEW_E, 'E.画廊开头')

# 旧的视频 / 图片两支 + 顶栏 + 收尾，整体换成 mediaPreviewPage 的分支体
OLD_E2 = (
    "          Video({ src: this.imageUri(this.imgPreview), controller: this.videoCtl })\n"
    "            .width('100%')\n"
    "            .height('100%')\n"
    "            .objectFit(ImageFit.Contain)\n"
    "            .controls(true)\n"
    "            .autoPlay(true)\n"
    "            .loop(false)\n"
    "            .onError(() => {\n"
    "              this.toast('无法播放这个视频（编码或封装格式不支持）');\n"
    "            })\n"
    "        } else {\n"
    "        Image(this.imageUri(this.imgPreview))\n"
    "          .width('100%')\n"
    "          .height('100%')\n"
    "          .objectFit(ImageFit.Contain)\n"
    "          .scale({ x: this.imgScale, y: this.imgScale })\n"
    "          .translate({ x: this.imgOffX, y: this.imgOffY })\n"
    "          .gesture(\n"
    "            GestureGroup(GestureMode.Parallel,\n"
    "              // 双指捏合缩放：1x ~ 8x\n"
    "              PinchGesture({ fingers: 2 })\n"
    "                .onActionUpdate((e: GestureEvent) => {\n"
    "                  const s: number = this.imgPinchBase * e.scale;\n"
    "                  this.imgScale = s < 1 ? 1 : (s > 8 ? 8 : s);\n"
    "                })\n"
    "                .onActionEnd(() => {\n"
    "                  this.imgPinchBase = this.imgScale;\n"
    "                  // 回到 1x 附近就顺手把位移归零，免得到处飘\n"
    "                  if (this.imgScale <= 1.02) {\n"
    "                    this.imgScale = 1;\n"
    "                    this.imgPinchBase = 1;\n"
    "                    this.imgOffX = 0;\n"
    "                    this.imgOffY = 0;\n"
    "                  }\n"
    "                }),\n"
    "              // 单指拖动：只在放大后生效（1x 时拖它就是浪费手势）\n"
    "              PanGesture({ fingers: 1, distance: 6 })\n"
    "                .onActionStart(() => {\n"
    "                  this.imgDragBaseX = this.imgOffX;\n"
    "                  this.imgDragBaseY = this.imgOffY;\n"
    "                })\n"
    "                .onActionUpdate((e: GestureEvent) => {\n"
    "                  if (this.imgScale > 1) {\n"
    "                    this.imgOffX = this.imgDragBaseX + e.offsetX;\n"
    "                    this.imgOffY = this.imgDragBaseY + e.offsetY;\n"
    "                  }\n"
    "                }),\n"
    "              // 双击：>1x 复位，=1x 放大到 2.5x（看细节不用两根手指）\n"
    "              TapGesture({ count: 2 })\n"
    "                .onAction(() => {\n"
    "                  if (this.imgScale > 1) {\n"
    "                    this.imgScale = 1;\n"
    "                    this.imgPinchBase = 1;\n"
    "                    this.imgOffX = 0;\n"
    "                    this.imgOffY = 0;\n"
    "                  } else {\n"
    "                    this.imgScale = 2.5;\n"
    "                    this.imgPinchBase = 2.5;\n"
    "                  }\n"
    "                }),\n"
    "              // 长按存相册（vivi 2026-10-01：「点开图片后长按就能选择保存到相册」）。\n"
    "              // 与捏合/拖动/双击并列在 Parallel 组里：长按时手指不动，\n"
    "              // PanGesture 的 distance:6 不会触发，互不打架。\n"
    "              LongPressGesture({ repeat: false, duration: 400 })\n"
    "                .onAction(() => {\n"
    "                  this.saveImageToAlbum(this.imgPreview, this.imgPreviewName);\n"
    "                })\n"
    "            )\n"
    "          )\n"
    "        }\n"
    "\n"
    "        // 顶栏：文件名 + 关闭。文件名占满剩余宽度，放不下就省略号\n"
    "        Row({ space: 10 }) {\n"
    "          Text(this.imgPreviewName)\n"
    "            .fontSize(13)\n"
    "            .fontColor('#EAEAEA')\n"
    "            .layoutWeight(1)\n"
    "            .maxLines(1)\n"
    "            .textOverflow({ overflow: TextOverflow.Ellipsis })\n"
    "          // 存相册放在这里而不是只挂在长按上：这是**唯一**能覆盖两个页面的入口\n"
    "          // （「文件」页的行已经是长按多选了，再挂长按会打架）。\n"
    "          // 长按气泡是快捷方式，这里才是兜底的那条路。\n"
    "          Button('存相册')\n"
    "            .fontSize(13)\n"
    "            .height(32)\n"
    "            .padding({ left: 14, right: 14 })\n"
    "            .backgroundColor('#33FFFFFF')\n"
    "            .fontColor(Color.White)\n"
    "            .onClick(() => this.saveImageToAlbum(this.imgPreview, this.imgPreviewName))\n"
    "          Button('关闭')\n"
    "            .fontSize(13)\n"
    "            .height(32)\n"
    "            .padding({ left: 14, right: 14 })\n"
    "            .backgroundColor('#33FFFFFF')\n"
    "            .fontColor(Color.White)\n"
    "            .onClick(() => this.closeMediaPreview())\n"
    "        }\n"
    "        .width('100%')\n"
    "        .padding({ left: 16, right: 16, top: this.topInset + 10 })\n"
    "      }\n"
    "      .width('100%')\n"
    "      .height('100%')\n"
    "      // 近黑底：看照片时最不干扰\n"
    "      .backgroundColor('#F0000000')\n"
    "    }\n"
    "  }\n"
)
NEW_E2 = (
    "          Video({ src: this.imageUri(path), controller: this.videoCtl })\n"
    "            .width('100%')\n"
    "            .height('100%')\n"
    "            .objectFit(ImageFit.Contain)\n"
    "            .controls(true)\n"
    "            .autoPlay(true)\n"
    "            .loop(false)\n"
    "            .onError(() => {\n"
    "              this.toast('无法播放这个视频（编码或封装格式不支持）');\n"
    "            })\n"
    "        } else {\n"
    "          // 非当前页：只出首帧（解不出来就留个 ▶，滑到这一页时才真正起播放器）\n"
    "          if (this.hasVideoThumb(path)) {\n"
    "            Image(this.videoThumbOf(path) as image.PixelMap)\n"
    "              .width('80%')\n"
    "              .height('80%')\n"
    "              .objectFit(ImageFit.Contain)\n"
    "          }\n"
    "          Text('▶')\n"
    "            .fontSize(48)\n"
    "            .fontColor('#FFFFFF')\n"
    "        }\n"
    "      } else {\n"
    "        Image(this.imageUri(path))\n"
    "          .width('100%')\n"
    "          .height('100%')\n"
    "          .objectFit(ImageFit.Contain)\n"
    "          .scale({ x: this.imgScale, y: this.imgScale })\n"
    "          .translate({ x: this.imgOffX, y: this.imgOffY })\n"
    "          .gesture(\n"
    "            GestureGroup(GestureMode.Parallel,\n"
    "              // 双指捏合缩放：1x ~ 8x\n"
    "              PinchGesture({ fingers: 2 })\n"
    "                .onActionUpdate((e: GestureEvent) => {\n"
    "                  const s: number = this.imgPinchBase * e.scale;\n"
    "                  this.imgScale = s < 1 ? 1 : (s > 8 ? 8 : s);\n"
    "                })\n"
    "                .onActionEnd(() => {\n"
    "                  this.imgPinchBase = this.imgScale;\n"
    "                  // 回到 1x 附近就顺手把位移归零，免得到处飘\n"
    "                  if (this.imgScale <= 1.02) {\n"
    "                    this.imgScale = 1;\n"
    "                    this.imgPinchBase = 1;\n"
    "                    this.imgOffX = 0;\n"
    "                    this.imgOffY = 0;\n"
    "                  }\n"
    "                }),\n"
    "              // 单指拖动：只在放大后生效（1x 时拖它就是浪费手势）\n"
    "              PanGesture({ fingers: 1, distance: 6 })\n"
    "                .onActionStart(() => {\n"
    "                  this.imgDragBaseX = this.imgOffX;\n"
    "                  this.imgDragBaseY = this.imgOffY;\n"
    "                })\n"
    "                .onActionUpdate((e: GestureEvent) => {\n"
    "                  if (this.imgScale > 1) {\n"
    "                    this.imgOffX = this.imgDragBaseX + e.offsetX;\n"
    "                    this.imgOffY = this.imgDragBaseY + e.offsetY;\n"
    "                  }\n"
    "                }),\n"
    "              // 双击：>1x 复位，=1x 放大到 2.5x（看细节不用两根手指）\n"
    "              TapGesture({ count: 2 })\n"
    "                .onAction(() => {\n"
    "                  if (this.imgScale > 1) {\n"
    "                    this.imgScale = 1;\n"
    "                    this.imgPinchBase = 1;\n"
    "                    this.imgOffX = 0;\n"
    "                    this.imgOffY = 0;\n"
    "                  } else {\n"
    "                    this.imgScale = 2.5;\n"
    "                    this.imgPinchBase = 2.5;\n"
    "                  }\n"
    "                }),\n"
    "              // 长按存相册（vivi 2026-10-01：「点开图片后长按就能选择保存到相册」）。\n"
    "              // 与捏合/拖动/双击并列在 Parallel 组里：长按时手指不动，\n"
    "              // PanGesture 的 distance:6 不会触发，互不打架。\n"
    "              LongPressGesture({ repeat: false, duration: 400 })\n"
    "                .onAction(() => {\n"
    "                  this.saveImageToAlbum(path, name);\n"
    "                })\n"
    "            )\n"
    "          )\n"
    "      }\n"
    "    }\n"
    "    .width('100%')\n"
    "    .height('100%')\n"
    "  }\n"
)
add(IDX, OLD_E2, NEW_E2, 'E2.画廊页体')

# ---------------- F. Index.ets：文件页缩略图 -> mediaThumb ----------------
OLD_F = (
    "                if (this.isMediaName(f.name)) {\n"
    "                  Stack() {\n"
    "                    if (this.isVideoName(f.name)) {\n"
    "                      // 视频：首帧 PixelMap（异步解，解完靠 `videoThumbTick` 刷新）\n"
    "                      Text('视频')\n"
    "                        .fontSize(11)\n"
    "                        .fontColor('#AAAAAA')\n"
    "                      if (this.hasVideoThumb(f.path)) {\n"
    "                        Image(this.videoThumbOf(f.path) as image.PixelMap)\n"
    "                          .width(48)\n"
    "                          .height(48)\n"
    "                          .objectFit(ImageFit.Cover)\n"
    "                      }\n"
    "                      Text('▶')\n"
    "                        .fontSize(16)\n"
    "                        .fontColor('#FFFFFF')\n"
    "                    } else {\n"
    "                      Text('图片')\n"
    "                        .fontSize(11)\n"
    "                        .fontColor('#AAAAAA')\n"
    "                      Image(this.imageUri(f.path))\n"
    "                        .width(48)\n"
    "                        .height(48)\n"
    "                        .objectFit(ImageFit.Cover)\n"
    "                        .sourceSize({ width: 96, height: 96 })\n"
    "                    }\n"
    "                  }\n"
    "                  .width(48)\n"
    "                  .height(48)\n"
    "                  .backgroundColor('#EFF2F6')\n"
    "                  .borderRadius(8)\n"
    "                  .clip(true)\n"
    "                }\n"
)
NEW_F = (
    "                if (this.isMediaName(f.name)) {\n"
    "                  // 5.0.31：等比缩略图（见 mediaThumb 的注释）\n"
    "                  this.mediaThumb(f.path, 48)\n"
    "                }\n"
)
add(IDX, OLD_F, NEW_F, 'F.文件页缩略图')

# ---------------- G. Index.ets：文件页点击进入画廊 ----------------
OLD_G = (
    "                } else if (this.isMediaName(f.name)) {\n"
    "                  // 普通态：图片/视频点一下进全屏预览（视频走播放器）；\n"
    "                  // 其它类型不做任何事（避免误触）\n"
    "                  this.openMediaPreview(f.path, f.name);\n"
    "                }\n"
)
NEW_G = (
    "                } else if (this.isMediaName(f.name)) {\n"
    "                  // 普通态：图片/视频点一下进全屏预览（视频走播放器）；\n"
    "                  // 5.0.31：把**列表里所有媒体**都装进画廊，可左右滑；\n"
    "                  // 其它类型不做任何事（避免误触）\n"
    "                  this.openFileGallery(f);\n"
    "                }\n"
)
add(IDX, OLD_G, NEW_G, 'G.文件页点击')

# ---------------- H. Index.ets：聊天气泡 ----------------
OLD_H = (
    "  @Builder\n"
    "  chatFileBubble(m: ChatMessage, mediaPath: string) {\n"
    "    Column({ space: 2 }) {\n"
    "      Text(m.incoming ? '收到文件' : '已发送文件')\n"
    "        .fontSize(11)\n"
    "        .fontColor(m.incoming ? C_SUB : '#DCE8FF')\n"
    "      if (mediaPath.length > 0) {\n"
    "        // ⚠️ `.sourceSize()` 必须给：不压解码尺寸的话，聊天记录里每张图都会把\n"
    "        //    **整张原图**解进内存，200 条上限 = 几百 MB（同文件页的坑）。\n"
    "        Stack() {\n"
    "          if (this.isVideoName(m.content)) {\n"
    "            // 视频：首帧缩略图（`AVImageGenerator` 解出来的 PixelMap）。\n"
    "            // 还没解出来 / 解码失败 → 停在灰色占位，不显示空框。\n"
    "            Text('视频')\n"
    "              .fontSize(11)\n"
    "              .fontColor('#AAAAAA')\n"
    "            if (this.hasVideoThumb(mediaPath)) {\n"
    "              Image(this.videoThumbOf(mediaPath) as image.PixelMap)\n"
    "                .width(128)\n"
    "                .height(128)\n"
    "                .objectFit(ImageFit.Cover)\n"
    "            }\n"
    "            // 播放角标：盖在图上，一眼区分「图」和「视频」\n"
    "            Text('▶')\n"
    "              .fontSize(30)\n"
    "              .fontColor('#FFFFFF')\n"
    "          } else {\n"
    "            Text('图片')\n"
    "              .fontSize(11)\n"
    "              .fontColor('#AAAAAA')\n"
    "            Image(this.imageUri(mediaPath))\n"
    "              .width(128)\n"
    "              .height(128)\n"
    "              .objectFit(ImageFit.Cover)\n"
    "              .sourceSize({ width: 192, height: 192 })\n"
    "          }\n"
    "        }\n"
    "        .width(128)\n"
    "        .height(128)\n"
    "        .backgroundColor('#EFF2F6')\n"
    "        .borderRadius(8)\n"
    "        .clip(true)\n"
    "      }\n"
    "      Text(m.content)\n"
    "        .fontSize(15)\n"
    "        .fontColor(m.incoming ? C_TEXT : '#FFFFFF')\n"
    "        .maxLines(2)\n"
    "        .wordBreak(WordBreak.BREAK_ALL)\n"
    "        .textOverflow({ overflow: TextOverflow.Ellipsis })\n"
    "      if (m.incoming) {\n"
    "        // 只有「收到的」才给入口：收到的文件落在沙箱里，\n"
    "        // 系统「文件管理」看不到，不指路用户就找不到。\n"
    "        // 自己发出去的原文件还在用户自己手上，不需要跳。\n"
    "        Text(mediaPath.length === 0\n"
    "          ? '点击查看 ›'\n"
    "          : (this.isVideoName(m.content) ? '点击播放 · 长按存相册' : '点击看图 · 长按存相册'))\n"
    "          .fontSize(10)\n"
    "          .fontColor(C_PRIMARY)\n"
    "      }\n"
    "    }\n"
    "    .alignItems(HorizontalAlign.Start)\n"
    "    .constraintSize({ maxWidth: '78%' })\n"
    "    .padding({ left: 12, right: 12, top: 8, bottom: 8 })\n"
    "    .backgroundColor(m.incoming ? C_CARD : C_PRIMARY)\n"
    "    .borderRadius(10)\n"
    "    .onClick(() => {\n"
    "      // 长按过的这一小段时间里把 click 吃掉，防「存相册」连带弹出预览\n"
    "      if (Date.now() < this.clickMuteUntil) {\n"
    "        return;\n"
    "      }\n"
    "      if (mediaPath.length > 0) {\n"
    "        this.openMediaPreview(mediaPath, m.content);\n"
    "        return;\n"
    "      }\n"
    "      if (m.incoming) {\n"
    "        this.openFileTab();\n"
    "      }\n"
    "    })\n"
    "    // 长按存相册。⚠️ 只对**收到的图片**有意义：自己发出去的图不在沙箱里，\n"
    "    // 原图本来就在用户手上，再存一份是多余动作。\n"
    "    // ⚠️ 必须走 `.gesture(LongPressGesture)` —— 这个 SDK 的 ArkUI **没有**\n"
    "    //    `onLongPress` 这个 CommonMethod 属性，写 `.onLongPress()` 直接\n"
    "    //    编译报 `10505001 ... does not exist on type 'ColumnAttribute'`。\n"
    "    //    文件页的「长按进多选」本来就是这么写的，本轮抄漏了形态。\n"
    "    .gesture(\n"
    "      LongPressGesture({ repeat: false, duration: 400 })\n"
    "        .onAction(() => {\n"
    "          if (mediaPath.length === 0) {\n"
    "            return;\n"
    "          }\n"
    "          this.clickMuteUntil = Date.now() + 800;\n"
    "          this.saveImageToAlbum(mediaPath, m.content);\n"
    "        })\n"
    "    )\n"
    "  }\n"
)
NEW_H = (
    "  @Builder\n"
    "  chatFileBubble(m: ChatMessage, mediaPath: string) {\n"
    "    Column({ space: 2 }) {\n"
    "      Text(m.incoming ? '收到文件' : '已发送文件')\n"
    "        .fontSize(11)\n"
    "        .fontColor(m.incoming ? C_SUB : '#DCE8FF')\n"
    "      if (this.mediaCountOf(m.id) > 0) {\n"
    "        // 5.0.31：对端一次发来 N 张 —— **只出第一张**缩略图 + 「共 N 张」角标，\n"
    "        // 点开进画廊左右滑。一张一个气泡会把整屏刷满，这也是 vivi 要的形态。\n"
    "        Stack({ alignContent: Alignment.BottomEnd }) {\n"
    "          this.mediaThumb(this.mediaPathAt(m.id, 0), 128)\n"
    "          if (this.mediaCountOf(m.id) > 1) {\n"
    "            Text(`共 ${this.mediaCountOf(m.id)} 张`)\n"
    "              .fontSize(10)\n"
    "              .fontColor(Color.White)\n"
    "              .padding({ left: 6, right: 6, top: 2, bottom: 2 })\n"
    "              .borderRadius(9)\n"
    "              .backgroundColor('#99000000')\n"
    "              .margin({ right: 4, bottom: 4 })\n"
    "          }\n"
    "        }\n"
    "      } else if (mediaPath.length > 0) {\n"
    "        this.mediaThumb(mediaPath, 128)\n"
    "      }\n"
    "      Text(m.content)\n"
    "        .fontSize(15)\n"
    "        .fontColor(m.incoming ? C_TEXT : '#FFFFFF')\n"
    "        .maxLines(2)\n"
    "        .wordBreak(WordBreak.BREAK_ALL)\n"
    "        .textOverflow({ overflow: TextOverflow.Ellipsis })\n"
    "      if (m.incoming) {\n"
    "        // 只有「收到的」才给入口：收到的文件落在沙箱里，\n"
    "        // 系统「文件管理」看不到，不指路用户就找不到。\n"
    "        // 自己发出去的原文件还在用户自己手上，不需要跳。\n"
    "        Text(this.bubbleHintOf(m, mediaPath))\n"
    "          .fontSize(10)\n"
    "          .fontColor(C_PRIMARY)\n"
    "      }\n"
    "    }\n"
    "    .alignItems(HorizontalAlign.Start)\n"
    "    .constraintSize({ maxWidth: '78%' })\n"
    "    .padding({ left: 12, right: 12, top: 8, bottom: 8 })\n"
    "    .backgroundColor(m.incoming ? C_CARD : C_PRIMARY)\n"
    "    .borderRadius(10)\n"
    "    .onClick(() => {\n"
    "      // 长按过的这一小段时间里把 click 吃掉，防「存相册」连带弹出预览\n"
    "      if (Date.now() < this.clickMuteUntil) {\n"
    "        return;\n"
    "      }\n"
    "      if (this.mediaCountOf(m.id) > 0) {\n"
    "        this.openChatGallery(m.id, 0);\n"
    "        return;\n"
    "      }\n"
    "      if (mediaPath.length > 0) {\n"
    "        this.openMediaPreview(mediaPath, m.content);\n"
    "        return;\n"
    "      }\n"
    "      if (m.incoming) {\n"
    "        this.openFileTab();\n"
    "      }\n"
    "    })\n"
    "    // 长按存相册。⚠️ 只对**收到的图片**有意义：自己发出去的图不在沙箱里，\n"
    "    // 原图本来就在用户手上，再存一份是多余动作。\n"
    "    // ⚠️ 必须走 `.gesture(LongPressGesture)` —— 这个 SDK 的 ArkUI **没有**\n"
    "    //    `onLongPress` 这个 CommonMethod 属性，写 `.onLongPress()` 直接\n"
    "    //    编译报 `10505001 ... does not exist on type 'ColumnAttribute'`。\n"
    "    //    文件页的「长按进多选」本来就是这么写的，本轮抄漏了形态。\n"
    "    .gesture(\n"
    "      LongPressGesture({ repeat: false, duration: 400 })\n"
    "        .onAction(() => {\n"
    "          if (this.mediaCountOf(m.id) > 0) {\n"
    "            this.clickMuteUntil = Date.now() + 800;\n"
    "            this.saveImageToAlbum(this.mediaPathAt(m.id, 0),\n"
    "              Index.baseName(this.mediaPathAt(m.id, 0)));\n"
    "            return;\n"
    "          }\n"
    "          if (mediaPath.length === 0) {\n"
    "            return;\n"
    "          }\n"
    "          this.clickMuteUntil = Date.now() + 800;\n"
    "          this.saveImageToAlbum(mediaPath, m.content);\n"
    "        })\n"
    "    )\n"
    "  }\n"
    "\n"
    "  /**\n"
    "   * 5.0.31：等比缩略图（**保持原宽高比**）。\n"
    "   *\n"
    "   * 以前是写死 `width(128).height(128)` + `objectFit(Cover)`：非正方形原图\n"
    "   * 直接被**裁成正方形**，画面变形。现在：\n"
    "   *   ① 框尺寸按真实比例算（最长边 = maxSide，`thumbW/thumbH`）；\n"
    "   *   ② `objectFit` 改 **Contain** —— 比例还没量出来时（首次渲染）宁可留边也不裁；\n"
    "   *   ③ `sourceSize` 按**同一个比例**给（解码尺寸不压的话 40 张原图会整张进内存，" +
    "压成正方形又会把图拉变形 —— 两个坑都得躲）。\n"
    "   *\n"
    "   * @param maxSide 最长边（聊天气泡 128 / 文件页 48）\n"
    "   */\n"
    "  @Builder\n"
    "  mediaThumb(path: string, maxSide: number) {\n"
    "    Stack() {\n"
    "      // 占位（也是解码失败 / 还没解出来的样子），真图载入后盖住它\n"
    "      Text(this.isVideoName(path) ? '视频' : '图片')\n"
    "        .fontSize(11)\n"
    "        .fontColor('#AAAAAA')\n"
    "      if (this.isVideoName(path)) {\n"
    "        if (this.hasVideoThumb(path)) {\n"
    "          Image(this.videoThumbOf(path) as image.PixelMap)\n"
    "            .width(this.thumbW(path, maxSide))\n"
    "            .height(this.thumbH(path, maxSide))\n"
    "            .objectFit(ImageFit.Contain)\n"
    "        }\n"
    "        // 播放角标：盖在图上，一眼区分「图」和「视频」\n"
    "        Text('▶')\n"
    "          .fontSize(maxSide >= 100 ? 30 : 16)\n"
    "          .fontColor('#FFFFFF')\n"
    "      } else {\n"
    "        Image(this.imageUri(path))\n"
    "          .width(this.thumbW(path, maxSide))\n"
    "          .height(this.thumbH(path, maxSide))\n"
    "          .objectFit(ImageFit.Contain)\n"
    "          .sourceSize({\n"
    "            width: this.thumbW(path, maxSide) * 2,\n"
    "            height: this.thumbH(path, maxSide) * 2\n"
    "          })\n"
    "      }\n"
    "    }\n"
    "    .width(this.thumbW(path, maxSide))\n"
    "    .height(this.thumbH(path, maxSide))\n"
    "    .backgroundColor('#EFF2F6')\n"
    "    .borderRadius(8)\n"
    "    .clip(true)\n"
    "  }\n"
)
add(IDX, OLD_H, NEW_H, 'H.聊天气泡 + mediaThumb')

# ---------------- I. Index.ets：ForEach key 带上 thumbTick ----------------
OLD_I = (
    "          }, (m: ChatMessage) => `${m.id}|${this.videoThumbTick}|"
    "${this.chatMediaPaths.has(m.id) ? (this.chatMediaPaths.get(m.id) ?? '') : ''}`)\n"
)
NEW_I = (
    "          }, (m: ChatMessage) => `${m.id}|${this.videoThumbTick}|${this.thumbTick}|"
    "${this.mediaCountOf(m.id)}|"
    "${this.chatMediaPaths.has(m.id) ? (this.chatMediaPaths.get(m.id) ?? '') : ''}`)\n"
)
add(IDX, OLD_I, NEW_I, 'I.聊天 key')

OLD_I2 = (
    "          }, (f: ReceivedFile) => `${f.path}|${f.size}|${f.time}|"
    "${this.isFileSelected(f.path) ? 1 : 0}|${this.videoThumbTick}`)\n"
)
NEW_I2 = (
    "          }, (f: ReceivedFile) => `${f.path}|${f.size}|${f.time}|"
    "${this.isFileSelected(f.path) ? 1 : 0}|${this.videoThumbTick}|${this.thumbTick}`)\n"
)
add(IDX, OLD_I2, NEW_I2, 'I2.文件页 key')

# ---------------- J. Index.ets：refreshReceived 预热比例 ----------------
OLD_J = "    this.prewarmVideoThumbs(list);\n"
NEW_J = OLD_J + (
    "    // 5.0.31：缩略图按原图比例出框，先把比例量好（同步读头信息，不解码整图）\n"
    "    for (let i = 0; i < list.length; i++) {\n"
    "      if (this.isMediaName(list[i].name)) {\n"
    "        this.ensureMediaRatio(list[i].path);\n"
    "      }\n"
    "    }\n"
)
add(IDX, OLD_J, NEW_J, 'J.refreshReceived')

# ---------------- K. Index.ets：文件头补一行说明 ----------------
OLD_K = (
    "先弹「正在保存」并**让出一帧**再拷，否则连提示都画不出来 |\n"
    " */\n"
)
NEW_K = (
    "先弹「正在保存」并**让出一帧**再拷，否则连提示都画不出来 |\n"
    " *\n"
    " * ## 2026-10-01 第十轮（5.0.31，vivi 真机诉求）\n"
    " * | 诉求 | 落法 |\n"
    " * |---|---|\n"
    " *   ③ `objectFit` 改 `Contain` —— 比例没量出来时宁可留边也不裁；"
    "④ `sourceSize` 按同一比例给 |\n"    " * | 收到多个图片只显示第一张、点开左右滑动 | `TransferReport.fileNames` 带上整批名字 → `ChatMessage.files`（落盘也带）→ UI 逐个反查成路径 → 气泡出**第一张** + 「共 N 张」角标；点开进 `Swiper` 画廊，顶栏显示 `i/n`。⚠️ 非当前页的视频只出首帧（多个 Video 共用一个 controller 行为未定义） |\n"
    " * | ⚠️ 文件名里有换行怎么办 | `ChatMessage.files` 用 `\\n` 分隔（`MiniJson.quote` 会转义成 `\\n`），文件名本身不会出现换行 |\n"
    " */\n"
)
add(IDX, OLD_K, NEW_K, 'K.文件头')

# ---------------- L. LanService.ets ----------------
OLD_L = (
    "  /**\n"
    "   * 消息类型：`text` 普通文本 / `file` 文件传输记录。\n"
    "   * `file` 的气泡显示文件名且**可点击** —— 点了跳到「文件」页看刚收/刚发的文件。\n"
    "   */\n"
    "  kind: string = 'text';\n"
)
NEW_L = OLD_L + (
    "  /**\n"
    "   * 5.0.31：这一批的**全部文件名**（'\\n' 分隔，顺序 = 传输顺序）。\n"
    "   *\n"
    "   * ⚠️ 为什么要它：多发时 `content` 只是「N 个文件」，UI 拿不到任何一个名字，\n"
    "   *    于是既出不了缩略图、也没法做「点开左右滑」。老版本只能显示一行干文字。\n"
    "   *    单发时也填（长度 1），省得调用方分叉。\n"
    "   */\n"
    "  files: string = '';\n"
)
add(LAN, OLD_L, NEW_L, 'L.ChatMessage.files')

OLD_L2 = (
    "  private appendChat(\n"
    "    incoming: boolean, peerName: string, peerIp: string, content: string, source: string,\n"
    "    kind: string = 'text'\n"
    "  ): void {\n"
)
NEW_L2 = (
    "  private appendChat(\n"
    "    incoming: boolean, peerName: string, peerIp: string, content: string, source: string,\n"
    "    kind: string = 'text', files: string = ''\n"
    "  ): void {\n"
)
add(LAN, OLD_L2, NEW_L2, 'L2.appendChat 入参')

OLD_L3 = (
    "    m.source = source;\n"
    "    m.kind = kind;\n"
)
NEW_L3 = (
    "    m.source = source;\n"
    "    m.kind = kind;\n"
    "    m.files = files;\n"
)
add(LAN, OLD_L3, NEW_L3, 'L3.appendChat 赋值')

OLD_L4 = (
    "      this.appendChat(incoming, r.peer, this.transferPeerIp, r.fileName,\n"
    "        incoming ? 'device' : 'app', 'file');\n"
)
NEW_L4 = (
    "      this.appendChat(incoming, r.peer, this.transferPeerIp, r.fileName,\n"
    "        incoming ? 'device' : 'app', 'file', r.fileNames.join('\\n'));\n"
)
add(LAN, OLD_L4, NEW_L4, 'L4.onTransferReport')

OLD_L5 = (
    "        `\"kind\":${MiniJson.quote(m.kind)}}`);\n"
)
NEW_L5 = (
    "        `\"kind\":${MiniJson.quote(m.kind)},` +\n"
    "        `\"files\":${MiniJson.quote(m.files)}}`);\n"
)
add(LAN, OLD_L5, NEW_L5, 'L5.序列化')

OLD_L6 = (
    "      m.kind = LanService.chatStr(n, 'kind');\n"
)
NEW_L6 = (
    "      m.kind = LanService.chatStr(n, 'kind');\n"
    "      m.files = LanService.chatStr(n, 'files');\n"
)
add(LAN, OLD_L6, NEW_L6, 'L6.反序列化')

# ---------------- M. FileTransfer.ets ----------------
OLD_M = (
    "  fileName: string = '';\n"
    "  fileIndex: number = 1;\n"
)
NEW_M = (
    "  fileName: string = '';\n"
    "  /**\n"
    "   * 5.0.31：这一批的**全部文件名**（顺序 = 传输顺序）。\n"
    "   * ⚠️ 只在**终态**那一次上报里带（进度上报给它是没意义的重复数据）。\n"
    "   */\n"
    "  fileNames: string[] = [];\n"
    "  fileIndex: number = 1;\n"
)
add(FT, OLD_M, NEW_M, 'M.TransferReport.fileNames')

OLD_M2 = (
    "    done: boolean,\n"
    "    ok: boolean,\n"
    "    message: string\n"
    "  ): void {\n"
)
NEW_M2 = (
    "    done: boolean,\n"
    "    ok: boolean,\n"
    "    message: string,\n"
    "    names: string[] = []\n"
    "  ): void {\n"
)
add(FT, OLD_M2, NEW_M2, 'M2.report 入参')

OLD_M3 = (
    "    r.done = done;\n"
    "    r.ok = ok;\n"
    "    r.message = message;\n"
)
NEW_M3 = (
    "    r.done = done;\n"
    "    r.ok = ok;\n"
    "    r.message = message;\n"
    "    r.fileNames = names;\n"
)
add(FT, OLD_M3, NEW_M3, 'M3.report 赋值')

OLD_M4 = (
    "      FileTransfer.report(onReport, 'send', target.devName,\n"
    "        files.length === 1 ? files[0].name : `${files.length} 个文件`,\n"
    "        total, total, grandTotal, grandTotal, 100, true, true,\n"
    "        `已发送 ${FileTransfer.human(grandTotal)} 到 ${target.devName}`);\n"
)
NEW_M4 = (
    "      // 5.0.31：终态带上整批文件名，UI 才能给「N 个文件」那条记录出缩略图\n"
    "      const allNames: string[] = [];\n"
    "      for (let i = 0; i < files.length; i++) {\n"
    "        allNames.push(files[i].name);\n"
    "      }\n"
    "      FileTransfer.report(onReport, 'send', target.devName,\n"
    "        files.length === 1 ? files[0].name : `${files.length} 个文件`,\n"
    "        total, total, grandTotal, grandTotal, 100, true, true,\n"
    "        `已发送 ${FileTransfer.human(grandTotal)} 到 ${target.devName}`, allNames);\n"
)
add(FT, OLD_M4, NEW_M4, 'M4.send 终态')

OLD_M5 = (
    "      FileTransfer.report(onReport, 'recv', from.devName,\n"
    "        total === 1 ? items[0].name : `${total} 个文件`,\n"
    "        total, total, grand, grand, 100, true, true,\n"
    "        `已接收 ${total} 项，保存到 ${storage.describe}`);\n"
)
NEW_M5 = (
    "      FileTransfer.report(onReport, 'recv', from.devName,\n"
    "        total === 1 ? items[0].name : `${total} 个文件`,\n"
    "        total, total, grand, grand, 100, true, true,\n"
    "        `已接收 ${total} 项，保存到 ${storage.describe}`, names);\n"
)
add(FT, OLD_M5, NEW_M5, 'M5.recv 终态')

# ---------------- N. V5Transfer.ets ----------------
OLD_N = (
    "    done: boolean,\n"
    "    ok: boolean,\n"
    "    message: string\n"
    "  ): void {\n"
)
NEW_N = (
    "    done: boolean,\n"
    "    ok: boolean,\n"
    "    message: string,\n"
    "    names: string[] = []\n"
    "  ): void {\n"
)
add(V5, OLD_N, NEW_N, 'N.report 入参')

OLD_N2 = (
    "    r.done = done;\n"
    "    r.ok = ok;\n"
    "    r.message = message;\n"
)
NEW_N2 = (
    "    r.done = done;\n"
    "    r.ok = ok;\n"
    "    r.message = message;\n"
    "    r.fileNames = names;\n"
)
add(V5, OLD_N2, NEW_N2, 'N2.report 赋值')

OLD_N3 = (
    "      V5Transfer.report(onReport, 'send', target.devName,\n"
    "        files.length === 1 ? files[0].name : `${files.length} 个文件`,\n"
    "        total, total, grandTotal, grandTotal, 100, true, true,\n"
    "        `已发送 ${V5Transfer.human(grandTotal)} 到 ${target.devName}`);\n"
)
NEW_N3 = (
    "      const allNames: string[] = [];\n"
    "      for (let i = 0; i < files.length; i++) {\n"
    "        allNames.push(files[i].name);\n"
    "      }\n"
    "      V5Transfer.report(onReport, 'send', target.devName,\n"
    "        files.length === 1 ? files[0].name : `${files.length} 个文件`,\n"
    "        total, total, grandTotal, grandTotal, 100, true, true,\n"
    "        `已发送 ${V5Transfer.human(grandTotal)} 到 ${target.devName}`, allNames);\n"
)
add(V5, OLD_N3, NEW_N3, 'N3.v5 send 终态')

OLD_N4 = (
    "      V5Transfer.report(onReport, 'recv', from.devName,\n"
    "        items.length === 1 ? items[0].name : `${items.length} 个文件`,\n"
    "        items.length, items.length, grand, grand, 100, true, true,\n"
    "        `已接收 ${items.length} 项，保存到 ${storage.describe}`);\n"
)
NEW_N4 = (
    "      V5Transfer.report(onReport, 'recv', from.devName,\n"
    "        items.length === 1 ? items[0].name : `${items.length} 个文件`,\n"
    "        items.length, items.length, grand, grand, 100, true, true,\n"
    "        `已接收 ${items.length} 项，保存到 ${storage.describe}`, names);\n"
)
add(V5, OLD_N4, NEW_N4, 'N4.v5 recv 终态')

# ==================================================================
# 校验：old 必须恰好出现一次；new 此前不能存在
# ==================================================================
print('--- 校验 ---')
buf = {}
for path, old, new, tag in edits:
    s = docs[path]
    c = s.count(old)
    if c != 1:
        print('FAIL[%s] old 出现 %d 次（应为 1）' % (tag, c))
        sys.exit(1)
    if s.count(new) != 0:
        print('FAIL[%s] new 已存在（重复插入风险）' % tag)
        sys.exit(1)
    print('OK  %s' % tag)
    buf[path] = buf.get(path, s).replace(old, new, 1)

# 括号增量粗查（每个文件：圆括号/花括号净变化不应为负得离谱）
for path in buf:
    for op, cl in (('(', ')'), ('{', '}'), ('[', ']')):
        d0 = docs[path].count(op) - docs[path].count(cl)
        d1 = buf[path].count(op) - buf[path].count(cl)
        if d0 != d1:
            print('WARN %s: %s%s 净差 %d -> %d' % (os.path.basename(path), op, cl, d0, d1))

# ==================================================================
# 统一落盘
# ==================================================================
for path in buf:
    with io.open(path, 'w', encoding='utf-8', newline='') as f:
        f.write(buf[path])
    print('WROTE', path)
print('DONE 5.0.31')
